using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Xml;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TourPlanner.XmlGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class XmlWriterGenerator : IIncrementalGenerator
{
    private const string GenerateXmlAttributeName = "TourPlanner.Xml.GenerateXmlAttribute";
    private const string XmlAttributeName = "System.Xml.Serialization.XmlAttributeAttribute";
    private const string XmlElementName = "System.Xml.Serialization.XmlElementAttribute";
    private const string XmlIgnoreName = "System.Xml.Serialization.XmlIgnoreAttribute";
    private const string XmlRootName = "System.Xml.Serialization.XmlRootAttribute";

    private static readonly DiagnosticDescriptor TypeMustBePartial = new(
        "XMLGEN001",
        "XML-generated types must be partial",
        "Type '{0}' must be partial so its XML writer can be generated",
        "XmlGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedProperty = new(
        "XMLGEN002",
        "Property cannot be generated",
        "Property '{0}' cannot be generated: {1}",
        "XmlGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedDeclarationShape = new(
        "XMLGEN003",
        "Type declaration shape cannot be generated",
        "Type '{0}' cannot be generated: {1}",
        "XmlGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidXmlName = new(
        "XMLGEN004",
        "XML name is invalid",
        "XML name '{0}' for {1} is invalid",
        "XmlGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor NullableArray = new(
        "XMLGEN005",
        "XML-generated arrays must be non-nullable",
        "Array property '{0}' and its elements must be non-nullable",
        "XmlGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor GeneratedMemberCollision = new(
        "XMLGEN006",
        "Member collides with generated XML writer",
        "Member '{0}' on type '{1}' collides with a generated XML writer member",
        "XmlGeneration",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output => output.AddSource(
            "TourPlanner.Xml.GenerateXmlAttribute.g.cs",
            SourceText.From(
                """
                // <auto-generated />
                #nullable enable

                namespace TourPlanner.Xml
                {
                    [global::System.AttributeUsage(
                        global::System.AttributeTargets.Class |
                        global::System.AttributeTargets.Struct |
                        global::System.AttributeTargets.Interface |
                        global::System.AttributeTargets.Enum |
                        global::System.AttributeTargets.Delegate,
                        AllowMultiple = false,
                        Inherited = false)]
                    internal sealed class GenerateXmlAttribute : global::System.Attribute
                    {
                    }
                }
                """,
                Encoding.UTF8)));

        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
            GenerateXmlAttributeName,
            static (node, _) => node is BaseTypeDeclarationSyntax or DelegateDeclarationSyntax,
            static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);

        context.RegisterSourceOutput(types, static (output, type) => Generate(output, type));
    }

    private static void Generate(SourceProductionContext output, INamedTypeSymbol type)
    {
        var hasErrors = ValidateType(output, type);
        var properties = GetSerializableProperties(type);

        hasErrors |= ValidateXmlNames(output, type, properties);

        foreach (var property in properties)
        {
            hasErrors |= ValidateProperty(output, property);
        }

        if (hasErrors)
        {
            return;
        }

        output.AddSource(
            GetHintName(type),
            SourceText.From(BuildSource(type, properties), Encoding.UTF8));
    }

    private static bool ValidateType(SourceProductionContext output, INamedTypeSymbol type)
    {
        var hasErrors = false;

        if (type.TypeKind != TypeKind.Class)
        {
            ReportUnsupportedShape(output, type, "only classes are supported");
            hasErrors = true;
        }

        if (type.ContainingNamespace.IsGlobalNamespace)
        {
            ReportUnsupportedShape(output, type, "types in the global namespace are not supported");
            hasErrors = true;
        }

        if (type.ContainingType is not null)
        {
            ReportUnsupportedShape(output, type, "nested types are not supported");
            hasErrors = true;
        }

        if (type.Arity is not 0)
        {
            ReportUnsupportedShape(output, type, "generic types are not supported");
            hasErrors = true;
        }

        if (type.TypeKind == TypeKind.Class)
        {
            if (!IsPartial(type))
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    TypeMustBePartial,
                    GetLocation(type),
                    type.Name));
                hasErrors = true;
            }

            if (type.IsStatic)
            {
                ReportUnsupportedShape(output, type, "static classes are not supported");
                hasErrors = true;
            }

            if (IsFileLocal(type))
            {
                ReportUnsupportedShape(output, type, "file-local classes cannot be extended by generated source");
                hasErrors = true;
            }

            if (type.DeclaredAccessibility is not Accessibility.Public and not Accessibility.Internal)
            {
                ReportUnsupportedShape(output, type, "the class must have public or internal accessibility");
                hasErrors = true;
            }
        }

        hasErrors |= ReportMemberCollisions(output, type, "WriteToXml");
        hasErrors |= ReportMemberCollisions(output, type, "WriteXml");

        return hasErrors;
    }

    private static bool ValidateProperty(SourceProductionContext output, IPropertySymbol property)
    {
        var hasErrors = false;
        var xmlAttributeCount = CountAttributes(property, XmlAttributeName);
        var xmlElementCount = CountAttributes(property, XmlElementName);

        if (property.GetMethod is null)
        {
            ReportUnsupportedProperty(output, property, "the property has no getter");
            hasErrors = true;
        }

        if (!property.Parameters.IsEmpty)
        {
            ReportUnsupportedProperty(output, property, "indexers are not supported");
            hasErrors = true;
        }

        if (xmlAttributeCount > 1)
        {
            ReportUnsupportedProperty(output, property, "multiple XmlAttribute attributes are not supported");
            hasErrors = true;
        }

        if (xmlElementCount > 1)
        {
            ReportUnsupportedProperty(output, property, "multiple XmlElement attributes are not supported");
            hasErrors = true;
        }

        if (xmlAttributeCount is not 0 && xmlElementCount is not 0)
        {
            ReportUnsupportedProperty(output, property, "XmlAttribute and XmlElement cannot be combined");
            hasErrors = true;
        }

        if (property.Type is IArrayTypeSymbol array)
        {
            if (property.NullableAnnotation == NullableAnnotation.Annotated ||
                array.NullableAnnotation == NullableAnnotation.Annotated ||
                array.ElementNullableAnnotation == NullableAnnotation.Annotated)
            {
                output.ReportDiagnostic(Diagnostic.Create(
                    NullableArray,
                    GetLocation(property),
                    property.Name));
                hasErrors = true;
            }

            if (xmlAttributeCount is not 0)
            {
                ReportUnsupportedProperty(output, property, "arrays cannot be written as XML attributes");
                hasErrors = true;
            }

            if (!array.IsSZArray || array.Rank != 1)
            {
                ReportUnsupportedProperty(output, property, "only one-dimensional zero-based arrays are supported");
                hasErrors = true;
            }

            if (array.ElementType is not INamedTypeSymbol elementType ||
                elementType.TypeKind != TypeKind.Class ||
                !HasAttribute(elementType, GenerateXmlAttributeName))
            {
                ReportUnsupportedProperty(
                    output,
                    property,
                    $"array element type '{array.ElementType.ToDisplayString()}' is not a [GenerateXml] class");
                hasErrors = true;
            }

            return hasErrors;
        }

        if (!TryGetScalarKind(property.Type, out _))
        {
            ReportUnsupportedProperty(
                output,
                property,
                $"type '{property.Type.ToDisplayString()}' is not a supported XML scalar or generated-class array");
            hasErrors = true;
        }

        return hasErrors;
    }

    private static bool ValidateXmlNames(
        SourceProductionContext output,
        INamedTypeSymbol type,
        ImmutableArray<IPropertySymbol> properties)
    {
        var hasErrors = ValidateEffectiveNames(
            output,
            type,
            XmlRootName,
            type.Name,
            $"root of type '{type.Name}'");

        foreach (var property in properties)
        {
            var xmlAttributes = GetAttributes(property, XmlAttributeName);
            var xmlElements = GetAttributes(property, XmlElementName);

            if (xmlAttributes.IsEmpty && xmlElements.IsEmpty)
            {
                hasErrors |= ValidateXmlName(
                    output,
                    property.Name,
                    $"property '{property.Name}'",
                    GetLocation(property));
                continue;
            }

            if (!xmlAttributes.IsEmpty)
            {
                hasErrors |= ValidateEffectiveNames(
                    output,
                    property,
                    XmlAttributeName,
                    property.Name,
                    $"attribute property '{property.Name}'");
            }

            if (!xmlElements.IsEmpty)
            {
                hasErrors |= ValidateEffectiveNames(
                    output,
                    property,
                    XmlElementName,
                    property.Name,
                    $"element property '{property.Name}'");
            }
        }

        return hasErrors;
    }

    private static bool ValidateEffectiveNames(
        SourceProductionContext output,
        ISymbol symbol,
        string attributeName,
        string fallbackName,
        string targetDescription)
    {
        var attributes = GetAttributes(symbol, attributeName);
        if (attributes.IsEmpty)
        {
            return ValidateXmlName(output, fallbackName, targetDescription, GetLocation(symbol));
        }

        var hasErrors = false;
        foreach (var attribute in attributes)
        {
            var name = GetEffectiveXmlName(attribute, attributeName, fallbackName);

            hasErrors |= ValidateXmlName(
                output,
                name,
                targetDescription,
                attribute.ApplicationSyntaxReference?.GetSyntax(output.CancellationToken).GetLocation() ??
                GetLocation(symbol));
        }

        return hasErrors;
    }

    private static bool ValidateXmlName(
        SourceProductionContext output,
        string? name,
        string targetDescription,
        Location? location)
    {
        if (IsValidXmlName(name))
        {
            return false;
        }

        output.ReportDiagnostic(Diagnostic.Create(
            InvalidXmlName,
            location,
            name ?? "<null>",
            targetDescription));
        return true;
    }

    private static bool IsValidXmlName(string? name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return false;
        }

        try
        {
            XmlConvert.VerifyNCName(name);
            return true;
        }
        catch (XmlException)
        {
            return false;
        }
    }

    private static string BuildSource(INamedTypeSymbol type, ImmutableArray<IPropertySymbol> properties)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine();
        source.Append("namespace ").Append(GetNamespaceName(type.ContainingNamespace)).AppendLine();
        source.AppendLine("{");
        source.Append("    ").Append(GetAccessibility(type)).Append(" partial ")
            .Append(type.IsRecord ? "record class " : "class ")
            .Append(EscapeIdentifier(type.Name)).AppendLine();
        source.AppendLine("    {");
        source.AppendLine("        public string WriteToXml()");
        source.AppendLine("        {");
        source.AppendLine("            var builder = new global::System.Text.StringBuilder();");
        source.AppendLine("            var settings = new global::System.Xml.XmlWriterSettings");
        source.AppendLine("            {");
        source.AppendLine("                Indent = true,");
        source.AppendLine("                OmitXmlDeclaration = true");
        source.AppendLine("            };");
        source.AppendLine();
        source.AppendLine("            using (var textWriter = new global::System.IO.StringWriter(builder, global::System.Globalization.CultureInfo.InvariantCulture))");
        source.AppendLine("            using (var writer = global::System.Xml.XmlWriter.Create(textWriter, settings))");
        source.AppendLine("            {");
        source.Append("                WriteXml(writer, ").Append(ToLiteral(GetTypeElementName(type))).AppendLine(");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            return builder.ToString();");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        internal void WriteXml(global::System.Xml.XmlWriter writer, string elementName)");
        source.AppendLine("        {");
        source.AppendLine("            writer.WriteStartElement(elementName);");

        foreach (var property in properties.Where(static property => HasAttribute(property, XmlAttributeName)))
        {
            AppendAttributeWriter(source, property);
        }

        foreach (var property in properties.Where(static property => !HasAttribute(property, XmlAttributeName)))
        {
            AppendElementWriter(source, property);
        }

        source.AppendLine("            writer.WriteEndElement();");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        return source.ToString();
    }

    private static void AppendAttributeWriter(StringBuilder source, IPropertySymbol property)
    {
        var propertyAccess = "this." + EscapeIdentifier(property.Name);
        var name = GetMemberName(property, XmlAttributeName);
        TryGetScalarKind(property.Type, out var scalarKind);

        if (IsNullableScalar(property))
        {
            source.AppendLine("            {");
            source.Append("                if (").Append(propertyAccess).AppendLine(" is { } value)");
            source.AppendLine("                {");
            source.Append("                    writer.WriteAttributeString(").Append(ToLiteral(name)).Append(", ")
                .Append(GetScalarExpression(scalarKind, "value")).AppendLine(");");
            source.AppendLine("                }");
            source.AppendLine("            }");
            return;
        }

        source.Append("            writer.WriteAttributeString(").Append(ToLiteral(name)).Append(", ")
            .Append(GetScalarExpression(scalarKind, propertyAccess)).AppendLine(");");
    }

    private static void AppendElementWriter(StringBuilder source, IPropertySymbol property)
    {
        var propertyAccess = "this." + EscapeIdentifier(property.Name);
        var name = GetMemberName(property, XmlElementName);

        if (property.Type is IArrayTypeSymbol)
        {
            source.Append("            foreach (var item in ").Append(propertyAccess).AppendLine(")");
            source.AppendLine("            {");
            source.Append("                item.WriteXml(writer, ").Append(ToLiteral(name)).AppendLine(");");
            source.AppendLine("            }");
            return;
        }

        TryGetScalarKind(property.Type, out var scalarKind);
        if (IsNullableScalar(property))
        {
            source.AppendLine("            {");
            source.Append("                if (").Append(propertyAccess).AppendLine(" is { } value)");
            source.AppendLine("                {");
            source.Append("                    writer.WriteElementString(").Append(ToLiteral(name)).Append(", ")
                .Append(GetScalarExpression(scalarKind, "value")).AppendLine(");");
            source.AppendLine("                }");
            source.AppendLine("                else");
            source.AppendLine("                {");
            source.Append("                    writer.WriteStartElement(").Append(ToLiteral(name)).AppendLine(");");
            source.AppendLine("                    writer.WriteAttributeString(\"xsi\", \"nil\", \"http://www.w3.org/2001/XMLSchema-instance\", \"true\");");
            source.AppendLine("                    writer.WriteEndElement();");
            source.AppendLine("                }");
            source.AppendLine("            }");
            return;
        }

        source.Append("            writer.WriteElementString(").Append(ToLiteral(name)).Append(", ")
            .Append(GetScalarExpression(scalarKind, propertyAccess)).AppendLine(");");
    }

    private static string GetScalarExpression(ScalarKind scalarKind, string access)
    {
        return scalarKind switch
        {
            ScalarKind.String => access,
            ScalarKind.DateTime =>
                $"global::System.Xml.XmlConvert.ToString({access}, global::System.Xml.XmlDateTimeSerializationMode.RoundtripKind)",
            _ => $"global::System.Xml.XmlConvert.ToString({access})"
        };
    }

    private static bool TryGetScalarKind(ITypeSymbol type, out ScalarKind scalarKind)
    {
        if (type is INamedTypeSymbol
            {
                OriginalDefinition.SpecialType: SpecialType.System_Nullable_T,
                TypeArguments.Length: 1
            } nullable)
        {
            type = nullable.TypeArguments[0];
        }

        scalarKind = type.SpecialType switch
        {
            SpecialType.System_String => ScalarKind.String,
            SpecialType.System_Boolean => ScalarKind.Boolean,
            SpecialType.System_Byte => ScalarKind.Byte,
            SpecialType.System_SByte => ScalarKind.SByte,
            SpecialType.System_Int16 => ScalarKind.Int16,
            SpecialType.System_UInt16 => ScalarKind.UInt16,
            SpecialType.System_Int32 => ScalarKind.Int32,
            SpecialType.System_UInt32 => ScalarKind.UInt32,
            SpecialType.System_Int64 => ScalarKind.Int64,
            SpecialType.System_UInt64 => ScalarKind.UInt64,
            SpecialType.System_Single => ScalarKind.Single,
            SpecialType.System_Double => ScalarKind.Double,
            SpecialType.System_Decimal => ScalarKind.Decimal,
            SpecialType.System_DateTime => ScalarKind.DateTime,
            _ => IsSystemGuid(type) ? ScalarKind.Guid : ScalarKind.Unsupported
        };

        return scalarKind != ScalarKind.Unsupported;
    }

    private static bool IsSystemGuid(ITypeSymbol type)
    {
        return type is INamedTypeSymbol { Name: "Guid", Arity: 0 } namedType &&
               namedType.ContainingNamespace is
               {
                   Name: "System",
                   ContainingNamespace.IsGlobalNamespace: true
               };
    }

    private static bool IsNullableScalar(IPropertySymbol property)
    {
        return property.Type is INamedTypeSymbol
               {
                   OriginalDefinition.SpecialType: SpecialType.System_Nullable_T
               } ||
               property.Type.SpecialType == SpecialType.System_String &&
               property.NullableAnnotation == NullableAnnotation.Annotated;
    }

    private static ImmutableArray<IPropertySymbol> GetSerializableProperties(INamedTypeSymbol type)
    {
        return type.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property =>
                !property.IsStatic &&
                property.DeclaredAccessibility == Accessibility.Public &&
                !HasAttribute(property, XmlIgnoreName))
            .ToImmutableArray();
    }

    private static bool IsPartial(INamedTypeSymbol type)
    {
        var declarations = type.DeclaringSyntaxReferences
            .Select(static reference => reference.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .ToImmutableArray();

        return !declarations.IsEmpty && declarations.All(static declaration =>
            declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    private static bool IsFileLocal(INamedTypeSymbol type)
    {
        return type.DeclaringSyntaxReferences
            .Select(static reference => reference.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(static declaration => declaration.Modifiers.Any(SyntaxKind.FileKeyword));
    }

    private static bool ReportMemberCollisions(
        SourceProductionContext output,
        INamedTypeSymbol type,
        string memberName)
    {
        var collisions = type.GetMembers(memberName);
        foreach (var collision in collisions)
        {
            output.ReportDiagnostic(Diagnostic.Create(
                GeneratedMemberCollision,
                GetLocation(collision),
                memberName,
                type.Name));
        }

        return !collisions.IsEmpty;
    }

    private static void ReportUnsupportedShape(
        SourceProductionContext output,
        INamedTypeSymbol type,
        string reason)
    {
        output.ReportDiagnostic(Diagnostic.Create(
            UnsupportedDeclarationShape,
            GetLocation(type),
            type.Name,
            reason));
    }

    private static void ReportUnsupportedProperty(
        SourceProductionContext output,
        IPropertySymbol property,
        string reason)
    {
        output.ReportDiagnostic(Diagnostic.Create(
            UnsupportedProperty,
            GetLocation(property),
            property.Name,
            reason));
    }

    private static string GetTypeElementName(INamedTypeSymbol type)
    {
        return GetEffectiveXmlName(type, XmlRootName, type.Name);
    }

    private static string GetMemberName(IPropertySymbol property, string attributeName)
    {
        return GetEffectiveXmlName(property, attributeName, property.Name);
    }

    private static string GetEffectiveXmlName(ISymbol symbol, string attributeName, string fallbackName)
    {
        var attribute = GetAttributes(symbol, attributeName).FirstOrDefault();
        return attribute is null
            ? fallbackName
            : GetEffectiveXmlName(attribute, attributeName, fallbackName);
    }

    private static string GetEffectiveXmlName(
        AttributeData attribute,
        string attributeName,
        string fallbackName)
    {
        var nameProperty = attributeName == XmlAttributeName ? "AttributeName" : "ElementName";
        if (!TryGetNamedXmlName(attribute, nameProperty, out var name) &&
            !TryGetConstructorXmlName(attribute, out name))
        {
            return fallbackName;
        }

        return name is null || name.Length is 0 ? fallbackName : name;
    }

    private static bool TryGetNamedXmlName(
        AttributeData attribute,
        string nameProperty,
        out string? name)
    {
        foreach (var namedArgument in attribute.NamedArguments)
        {
            if (namedArgument.Key != nameProperty)
            {
                continue;
            }

#pragma warning disable AL1211 // Keeping the generator dependency-free avoids an analyzer load-context dependency.
            name = namedArgument.Value.Value as string;
#pragma warning restore AL1211
            return true;
        }

        name = null;
        return false;
    }

    private static bool TryGetConstructorXmlName(AttributeData attribute, out string? name)
    {
        if (attribute.AttributeConstructor is { } constructor)
        {
            for (var index = 0;
                 index < constructor.Parameters.Length && index < attribute.ConstructorArguments.Length;
                 index++)
            {
                if (constructor.Parameters[index].Type.SpecialType != SpecialType.System_String)
                {
                    continue;
                }

#pragma warning disable AL1211 // Keeping the generator dependency-free avoids an analyzer load-context dependency.
                name = attribute.ConstructorArguments[index].Value as string;
#pragma warning restore AL1211
                return true;
            }
        }

        name = null;
        return false;
    }

    private static ImmutableArray<AttributeData> GetAttributes(ISymbol symbol, string attributeName)
    {
        return symbol.GetAttributes()
            .Where(attribute => attribute.AttributeClass?.ToDisplayString() == attributeName)
            .ToImmutableArray();
    }

    private static int CountAttributes(ISymbol symbol, string attributeName)
    {
        return GetAttributes(symbol, attributeName).Length;
    }

    private static bool HasAttribute(ISymbol symbol, string attributeName)
    {
        return symbol.GetAttributes()
            .Any(attribute => attribute.AttributeClass?.ToDisplayString() == attributeName);
    }

    private static string GetNamespaceName(INamespaceSymbol namespaceSymbol)
    {
        var names = new Stack<string>();
        for (var current = namespaceSymbol;
             !current.IsGlobalNamespace;
             current = current.ContainingNamespace)
        {
            names.Push(EscapeIdentifier(current.Name));
        }

        return string.Join(".", names);
    }

    private static string GetAccessibility(INamedTypeSymbol type)
    {
        return type.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
    }

    private static string EscapeIdentifier(string identifier)
    {
        return SyntaxFacts.GetKeywordKind(identifier) != SyntaxKind.None ||
               SyntaxFacts.GetContextualKeywordKind(identifier) != SyntaxKind.None
            ? "@" + identifier
            : identifier;
    }

    private static string ToLiteral(string value)
    {
        return SymbolDisplay.FormatLiteral(value, quote: true);
    }

    private static string GetHintName(INamedTypeSymbol type)
    {
        var identity = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var readable = new string(identity
            .Select(static character => char.IsLetterOrDigit(character) ? character : '_')
            .Take(80)
            .ToArray());
        var hash = GetStableHash(identity);
        return $"{readable}_{hash.ToString("X16", CultureInfo.InvariantCulture)}.XmlWriter.g.cs";
    }

    private static ulong GetStableHash(string value)
    {
        unchecked
        {
            const ulong offsetBasis = 14695981039346656037;
            const ulong prime = 1099511628211;
            var hash = offsetBasis;

            foreach (var character in value)
            {
                hash ^= character;
                hash *= prime;
            }

            return hash;
        }
    }

    private static Location? GetLocation(ISymbol symbol)
    {
        return symbol.Locations.FirstOrDefault(static location => location.IsInSource) ??
               symbol.Locations.FirstOrDefault();
    }

    private enum ScalarKind
    {
        Unsupported,
        String,
        Boolean,
        Byte,
        SByte,
        Int16,
        UInt16,
        Int32,
        UInt32,
        Int64,
        UInt64,
        Single,
        Double,
        Decimal,
        Guid,
        DateTime
    }
}
