name: Tests and Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Install libgdiplus for System.Drawing on Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdiplus
          sudo ln -s /usr/lib/libgdiplus.so /usr/lib/libgdiplus.dll

      - name: Test with coverage
        run: |
          dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ANcpLua/TourPlanner
          files: '**/coverage.cobertura.xml'
